"use client";

export type SpellMatch = {
  start: number;
  end: number;
  wrong: string;
  suggestion: string;
  rule?: string;
};

type Token = { w: string; i: number; l: number };

const FR_WORD_CHARS = /[A-Za-zÀ-ÖØ-öø-ÿ'\-]/;

const tokensOf = (text: string): Token[] => {
  const res: Token[] = [];
  let i = 0;
  const n = text.length;
  while (i < n) {
    const c = text[i];
    if (FR_WORD_CHARS.test(c)) {
      let j = i;
      while (j < n && FR_WORD_CHARS.test(text[j])) j++;
      const w = text.slice(i, j);
      if (w.length >= 2) res.push({ w, i, l: j - i });
      i = j;
    } else {
      i++;
    }
  }
  return res;
};

const LIGNE = (w: string) => w.toLowerCase();

const ERRORS_EXACT_LOWER: Record<string, { s: string; r?: string }> = {
  // 🔴 Accents les plus courants
  "a": { s: "à", r: "a (verbe avoir) / à (préposition)" },
  "ete": { s: "été", r: "été (nom/adj + accent aigu)" },
  "etre": { s: "être", r: "être — voyelles nasales accents" },
  "etais": { s: "étais", r: "étais / imparfait être" },
  "etait": { s: "était", r: "était — 3e sg imparfait être" },
  "etaient": { s: "étaient", r: "étaient — 3e pluriel imparfait" },
  "etant": { s: "étant", r: "étant — gérondif" },
  "etat": { s: "état", r: "état (nom)" },
  "francais": { s: "français", r: "français — c cédille" },
  "francaise": { s: "française", r: "française — féminin" },
  "ca": { s: "ça", r: "ça (démonstratif) / ça = cela" },
  "mais": { s: "mais", r: "" },
  "laisser": { s: "laisser" },
  "allais": { s: "allais", r: "allais — imparfait aller" },
  "allait": { s: "allait", r: "allait — 3e sg" },
  "allaient": { s: "allaient", r: "allaient — pluriel" },
  "deja": { s: "déjà", r: "déjà — accent grave" },
  "bien": { s: "bien" },
  "tres": { s: "très", r: "très — accent grave" },
  "aime": { s: "aime", r: "" },
  "faite": { s: "faite", r: "faite — accord participe féminin" },
  "fait": { s: "fait" },
  "faits": { s: "faits" },
  "faites": { s: "faites" },
  "suis": { s: "suis" },
  "est": { s: "est" },
  "sommes": { s: "sommes" },
  "etes": { s: "êtes", r: "êtes — 2e pluriel être — accent circonflexe" },
  "sont": { s: "sont" },
  "dois": { s: "dois" },
  "doit": { s: "doit" },
  "devons": { s: "devons" },
  "devez": { s: "devez" },
  "doivent": { s: "doivent" },
  "ai": { s: "ai" },
  "as": { s: "as" },
  "avons": { s: "avons" },
  "avez": { s: "avez" },
  "ont": { s: "ont" },
  "peux": { s: "peux" },
  "peut": { s: "peut" },
  "pouvons": { s: "pouvons" },
  "pouvez": { s: "pouvez" },
  "peuvent": { s: "peuvent" },
  "veux": { s: "veux" },
  "veut": { s: "veut" },
  "voulons": { s: "voulons" },
  "voulez": { s: "voulez" },
  "veulent": { s: "veulent" },
  "vais": { s: "vais" },
  "vas": { s: "vas" },
  "va": { s: "va" },
  "allons": { s: "allons" },
  "allez": { s: "allez" },
  "vont": { s: "vont" },
  "sais": { s: "sais" },
  "sait": { s: "sait" },
  "savons": { s: "savons" },
  "savez": { s: "savez" },
  "savent": { s: "savent" },
  "connais": { s: "connais" },
  "connait": { s: "connaît", r: "connaît — 3e sg présent connaître (accent circonflexe sur le î)" },
  "connaissons": { s: "connaissons" },
  "connaissez": { s: "connaissez" },
  "connaissent": { s: "connaissent" },
  "recu": { s: "reçu", r: "reçu — participe passé recevoir — u accent grave + ç" },
  "recus": { s: "reçus", r: "reçus — pluriel masc" },
  "recue": { s: "reçue", r: "reçue — accord féminin" },
  "recues": { s: "reçues", r: "reçues — accord féminin pluriel" },
  "aller": { s: "aller" },
  "ou": { s: "où", r: "où (adverbe lieu) — accent grave / ou = conjonction" },
  "oubli": { s: "oubli" },
  "coute": { s: "coûte", r: "coûte — prix, accent circonflexe û" },
  "couter": { s: "coûter", r: "coûter — infinitif" },
  "couteux": { s: "coûteux", r: "coûteux — cher" },
  "gout": { s: "goût", r: "goût — saveur / û accent circonflexe" },
  "gouter": { s: "goûter", r: "goûter — verbe" },
  "surnom": { s: "surnom" },
  "confort": { s: "confort" },
  "role": { s: "rôle", r: "rôle — accent circonflexe ô" },
  "hotel": { s: "hôtel", r: "hôtel — ^ sur ô" },
  "hopital": { s: "hôpital", r: "hôpital — hôpital accent" },
  "hopitaux": { s: "hôpitaux", r: "hôpitaux — pluriel" },
  "foret": { s: "forêt", r: "forêt — ê accent circonflexe" },
  "fetes": { s: "fêtes", r: "fêtes — pluriel" },
  "fete": { s: "fête", r: "fête — nom/verbe fêter" },
  "feter": { s: "fêter", r: "fêter — infinitif" },
  "tete": { s: "tête", r: "tête — corps, ê accent" },
  "fenetre": { s: "fenêtre", r: "fenêtre — ê" },
  "cretes": { s: "crêtes", r: "crêtes — montagnes" },
  "releve": { s: "relève", r: "relève — e accent aigu" },
  "releves": { s: "relèves", r: "relèves pluriel" },
  "tresor": { s: "trésor", r: "trésor — é accent aigu" },
  "mecontent": { s: "mécontent", r: "mécontent — é préfixe mé-" },
  "mecontentement": { s: "mécontentement", r: "mécontentement" },
  "evenement": { s: "événement", r: "événement — deux é" },
  "evenements": { s: "événements", r: "événements pluriel" },
  "deces": { s: "décès", r: "décès — accent aigu + c cédille" },
  "ne": { s: "né", r: "né — participe naître — é accent aigu" },
  "nee": { s: "née", r: "née — accord féminin" },
  "nes": { s: "nés", r: "nés" },
  "nees": { s: "nées", r: "nées — féminin pluriel" },
  "repondre": { s: "répondre", r: "répondre — é accent" },
  "reponse": { s: "réponse", r: "réponse — nom" },
  "reponses": { s: "réponses", r: "réponses — pluriel" },
  "ce": { s: "ce" },
  "cet": { s: "cet", r: "cet + mot commençant par voyelle ou h muet" },
  "cette": { s: "cette" },
  "ces": { s: "ces" },
  "tout": { s: "tout" },
  "tous": { s: "tous" },
  "toute": { s: "toute" },
  "toutes": { s: "toutes" },
  "leur": { s: "leur" },
  "leurs": { s: "leurs" },
  "son": { s: "son" },
  "sa": { s: "sa" },
  "ses": { s: "ses" },
  "mon": { s: "mon" },
  "ma": { s: "ma" },
  "mes": { s: "mes" },
  "ton": { s: "ton" },
  "ta": { s: "ta" },
  "tes": { s: "tes" },
  "notre": { s: "notre" },
  "nos": { s: "nos" },
  "votre": { s: "votre" },
  "vos": { s: "vos" },
  "jour": { s: "jour" },
  "jours": { s: "jours" },
  "aujourd'hui": { s: "aujourd'hui" },
  "aujourdhui": { s: "aujourd'hui", r: "aujourd'hui — apostrophe obligatoire" },
  "bienvenue": { s: "bienvenue", r: "bienvenue — nom féminin" },
  "bienvenu": { s: "bienvenu", r: "bienvenu — masculin" },
  "bienvenus": { s: "bienvenus", r: "bienvenus — pluriel masc" },
  "bienvenues": { s: "bienvenues", r: "bienvenues — pluriel féminin" },
  "maintenant": { s: "maintenant" },
  "quand": { s: "quand", r: "quand (conjonction temporelle)" },
  "quant": { s: "quant", r: "quant à = en ce qui concerne — avec t" },
  "qu'en": { s: "qu'en", r: "qu'en (pronom)" },
  "plus": { s: "plus" },
  "moins": { s: "moins" },
  "trop": { s: "trop" },
  "beaucoup": { s: "beaucoup" },
  "peu": { s: "peu" },
  "quelque": { s: "quelque" },
  "quelques": { s: "quelques" },
  "quelqu'un": { s: "quelqu'un", r: "quelqu'un — apostrophe" },
  "quelquun": { s: "quelqu'un", r: "quelqu'un — apostrophe manquante" },
  "personne": { s: "personne" },
  "chacun": { s: "chacun" },
  "chacune": { s: "chacune" },
  "quoi": { s: "quoi" },
  "donc": { s: "donc" },
  "alors": { s: "alors" },
  "puis": { s: "puis" },
  "ensuite": { s: "ensuite" },
  "finalement": { s: "finalement" },
  "enfin": { s: "enfin" },
  "d'abord": { s: "d'abord", r: "d'abord — apostrophe + a accent" },
  "dabord": { s: "d'abord", r: "d'abord — apostrophe manquante + a accent" },
  "premierement": { s: "premièrement", r: "premièrement — è accent sur premier" },
  "deuxiemement": { s: "deuxièmement", r: "deuxièmement — è accent sur deuxième" },
  "troisiemement": { s: "troisièmement", r: "troisièmement" },
  "dernierement": { s: "dernièrement", r: "dernièrement — è" },
  "probablement": { s: "probablement" },
  "eventuellement": { s: "éventuellement", r: "éventuellement — é accent" },
  "effectivement": { s: "effectivement" },
  "actuellement": { s: "actuellement" },
  "precisement": { s: "précisément", r: "précisément — é accent aigu" },
  "regulièrement": { s: "régulièrement", r: "régulièrement — é" },
  "particulierement": { s: "particulièrement", r: "particulièrement — è" },
  "exactement": { s: "exactement" },
  "surtout": { s: "surtout" },
  "notamment": { s: "notamment" },
  "en particulier": { s: "en particulier" },
  "par exemple": { s: "par exemple" },
  "parcontre": { s: "par contre", r: "par contre — DEUX MOTS, jamais un" },
  "parcour": { s: "parcours", r: "parcours — s final" },
  "parcours": { s: "parcours" },
  "cours": { s: "cours" },
  "course": { s: "course" },
  "source": { s: "source" },
  "ressource": { s: "ressource" },
  "ressources": { s: "ressources" },
  "choix": { s: "choix" },
  "choixs": { s: "choix", r: "choix — pas de s au pluriel, choix est invariable" },
  "prix": { s: "prix" },
  "prixs": { s: "prix", r: "prix — invariable pluriel" },
  "nez": { s: "nez" },
  "nezs": { s: "nez", r: "nez — invariable" },
  "fois": { s: "fois" },
  "foix": { s: "fois", r: "fois (temps/occasion) / foix = orthographe invalide pour ce sens" },
  "vois": { s: "vois" },
  "voit": { s: "voit" },
  "voyons": { s: "voyons" },
  "voyez": { s: "voyez" },
  "voient": { s: "voient" },
  "vue": { s: "vue" },
  "vu": { s: "vu" },
  "vus": { s: "vus" },
  "vues": { s: "vues" },
  "vient": { s: "vient" },
  "viennent": { s: "viennent" },
  "venir": { s: "venir" },
  "venu": { s: "venu" },
  "venue": { s: "venue" },
  "venus": { s: "venus" },
  "venues": { s: "venues" },
  "partir": { s: "partir" },
  "parti": { s: "parti" },
  "partie": { s: "partie" },
  "partis": { s: "partis" },
  "parties": { s: "parties" },
  "sortir": { s: "sortir" },
  "sorti": { s: "sorti" },
  "sortie": { s: "sortie" },
  "sortis": { s: "sortis" },
  "sorties": { s: "sorties" },
  "montre": { s: "montre" },
  "montrer": { s: "montrer" },
  "parle": { s: "parle" },
  "parler": { s: "parler" },
  "finir": { s: "finir" },
  "fini": { s: "fini" },
  "finie": { s: "finie" },
  "finis": { s: "finis" },
  "finies": { s: "finies" },
  "grand": { s: "grand" },
  "grande": { s: "grande" },
  "grands": { s: "grands" },
  "grandes": { s: "grandes" },
  "petit": { s: "petit" },
  "petite": { s: "petite" },
  "petits": { s: "petits" },
  "petites": { s: "petites" },
  "beau": { s: "beau" },
  "bel": { s: "bel", r: "bel — devant voyelle / h muet" },
  "belle": { s: "belle" },
  "beaux": { s: "beaux" },
  "belles": { s: "belles" },
  "nouveau": { s: "nouveau" },
  "nouvel": { s: "nouvel", r: "nouvel — devant voyelle/h muet" },
  "nouvelle": { s: "nouvelle" },
  "nouveaux": { s: "nouveaux" },
  "nouvelles": { s: "nouvelles" },
  "vieux": { s: "vieux" },
  "vieil": { s: "vieil", r: "vieil — devant voyelle/h muet" },
  "vieille": { s: "vieille" },
  "vielle": { s: "vieille", r: "vieille — orthographe, deux l" },
  "vieuxs": { s: "vieux", r: "vieux — invariable pluriel masc" },
  "faux": { s: "faux" },
  "fausse": { s: "fausse" },
  "fausses": { s: "fausses" },
  "difficile": { s: "difficile" },
  "facile": { s: "facile" },
  "important": { s: "important" },
  "importante": { s: "importante" },
  "importants": { s: "importants" },
  "importantes": { s: "importantes" },
  "interessant": { s: "intéressant", r: "intéressant — é accent aigu sur préfixe inté-" },
  "interessante": { s: "intéressante", r: "intéressante féminin" },
  "interessants": { s: "intéressants", r: "intéressants pluriel" },
  "interessantes": { s: "intéressantes", r: "intéressantes féminin pluriel" },
  "interet": { s: "intérêt", r: "intérêt — é accent aigu + ê" },
  "interets": { s: "intérêts", r: "intérêts pluriel" },
  "excellent": { s: "excellent" },
  "excellente": { s: "excellente" },
  "excellents": { s: "excellents" },
  "bon": { s: "bon" },
  "bonne": { s: "bonne" },
  "bons": { s: "bons" },
  "bonnes": { s: "bonnes" },
  "meilleur": { s: "meilleur" },
  "meilleure": { s: "meilleure" },
  "meilleurs": { s: "meilleurs" },
  "meilleures": { s: "meilleures" },
  "mauvais": { s: "mauvais" },
  "mauvaise": { s: "mauvaise" },
  "mauvaises": { s: "mauvaises" },
  "pire": { s: "pire" },
  "pires": { s: "pires" },
  "moindre": { s: "moindre" },
  "moindres": { s: "moindres" },
  "autre": { s: "autre" },
  "autres": { s: "autres" },
  "autrui": { s: "autrui" },
  "seul": { s: "seul" },
  "seule": { s: "seule" },
  "seuls": { s: "seuls" },
  "seules": { s: "seules" },
  "jeune": { s: "jeune" },
  "jeunes": { s: "jeunes" },
  "jeunne": { s: "jeune", r: "jeune — UN SEUL n — jeunne = orthographe invalide" },
  "jeunnes": { s: "jeunes", r: "jeunes — un seul n" },
  "ville": { s: "ville" },
  "villes": { s: "villes" },
  "village": { s: "village" },
  "villages": { s: "villages" },
  "pays": { s: "pays" },
  "payss": { s: "pays", r: "pays — invariable pluriel" },
  "region": { s: "région", r: "région — é accent" },
  "regions": { s: "régions", r: "régions" },
  "province": { s: "province" },
  "provinces": { s: "provinces" },
  "monde": { s: "monde" },
  "univers": { s: "univers" },
  "universite": { s: "université", r: "université — é accent" },
  "universites": { s: "universités", r: "universités pluriel" },
  "ecole": { s: "école", r: "école — é accent aigu" },
  "ecoles": { s: "écoles", r: "écoles pluriel" },
  "college": { s: "collège", r: "collège — è accent grave + deux l" },
  "colleges": { s: "collèges", r: "collèges pluriel" },
  "lycee": { s: "lycée", r: "lycée — é accent" },
  "lycees": { s: "lycées", r: "lycées pluriel" },
  "etude": { s: "étude", r: "étude — é accent" },
  "etudes": { s: "études", r: "études pluriel" },
  "etudiant": { s: "étudiant", r: "étudiant — é accent aigu" },
  "etudiante": { s: "étudiante", r: "étudiante féminin" },
  "etudiants": { s: "étudiants", r: "étudiants pluriel" },
  "etudiantes": { s: "étudiantes", r: "étudiantes féminin pluriel" },
  "professeur": { s: "professeur" },
  "professeurs": { s: "professeurs" },
  "enseignant": { s: "enseignant" },
  "enseignante": { s: "enseignante" },
  "enseignants": { s: "enseignants" },
  "enseignantes": { s: "enseignantes" },
  "eleve": { s: "élève", r: "élève — è accent grave" },
  "eleves": { s: "élèves", r: "élèves pluriel" },
  "travail": { s: "travail" },
  "travaille": { s: "travaille", r: "travaille — verbe travailler, 1e/3e sg présent" },
  "travailles": { s: "travailles" },
  "travaillons": { s: "travaillons" },
  "travaillez": { s: "travaillez" },
  "travaillent": { s: "travaillent" },
  "travailler": { s: "travailler" },
  "travails": { s: "travaux", r: "travaux — pluriel irrégulier travail → travaux" },
  "cheval": { s: "cheval" },
  "chevaux": { s: "chevaux", r: "chevaux — pluriel irrégulier -al → -aux" },
  "chevals": { s: "chevaux", r: "chevaux — -al → -aux jamais -als" },
  "animal": { s: "animal" },
  "animaux": { s: "animaux", r: "animaux — pluriel -al→-aux" },
  "animals": { s: "animaux", r: "animaux — -als invalide ici" },
  "journal": { s: "journal" },
  "journaux": { s: "journaux", r: "journaux — pluriel -al→-aux" },
  "journals": { s: "journaux", r: "journaux — -als invalide" },
  "national": { s: "national" },
  "nationaux": { s: "nationaux", r: "nationaux — pluriel -al→-aux" },
  "nationale": { s: "nationale" },
  "nationales": { s: "nationales" },
  "internationale": { s: "internationale" },
  "internationales": { s: "internationales" },
  "international": { s: "international" },
  "internationaux": { s: "internationaux", r: "internationaux — pluriel" },
  "generale": { s: "générale", r: "générale — é accent aigu sur gé-" },
  "general": { s: "général", r: "général — é accent" },
  "generaux": { s: "généraux", r: "généraux — pluriel général → généraux" },
  "familial": { s: "familial" },
  "famillial": { s: "familial", r: "familial — UN l seulement, familiale avec deux l mais masc = 1" },
  "familiale": { s: "familiale" },
  "familiales": { s: "familiales" },
  "sociaux": { s: "sociaux" },
  "sociale": { s: "sociale" },
  "sociales": { s: "sociales" },
  "social": { s: "social" },
  "culturel": { s: "culturel" },
  "culturelle": { s: "culturelle" },
  "culturelles": { s: "culturelles" },
  "culturels": { s: "culturels" },
  "personnel": { s: "personnel" },
  "personnelle": { s: "personnelle" },
  "personnelles": { s: "personnelles" },
  "personnels": { s: "personnels" },
  "professionnel": { s: "professionnel" },
  "professionnelle": { s: "professionnelle" },
  "professionnelles": { s: "professionnelles" },
  "professionnels": { s: "professionnels" },
  "technique": { s: "technique" },
  "techniques": { s: "techniques" },
  "technologie": { s: "technologie" },
  "scientifique": { s: "scientifique" },
  "scientifiques": { s: "scientifiques" },
  "medical": { s: "médical", r: "médical — é accent" },
  "medicale": { s: "médicale", r: "médicale — é + féminin" },
  "hospitalier": { s: "hospitalier" },
  "sante": { s: "santé", r: "santé — é accent aigu final" },
  "santes": { s: "santés", r: "santés — pluriel rare" },
  "maladie": { s: "maladie" },
  "maladies": { s: "maladies" },
  "symptome": { s: "symptôme", r: "symptôme — ô accent circonflexe" },
  "symptomes": { s: "symptômes", r: "symptômes pluriel" },
  "medicament": { s: "médicament", r: "médicament — é accent aigu" },
  "medicaments": { s: "médicaments", r: "médicaments pluriel" },
  "traitement": { s: "traitement" },
  "traitements": { s: "traitements" },
  "docteur": { s: "docteur" },
  "medecin": { s: "médecin", r: "médecin — é accent aigu + ê" },
  "medecins": { s: "médecins", r: "médecins pluriel" },
  "patient": { s: "patient" },
  "patiente": { s: "patiente" },
  "patients": { s: "patients" },
  "patientes": { s: "patientes" },
  "service": { s: "service" },
  "services": { s: "services" },
  "produit": { s: "produit" },
  "produits": { s: "produits" },
  "produite": { s: "produite" },
  "produites": { s: "produites" },
  "produire": { s: "produire" },
  "acheter": { s: "acheter" },
  "achete": { s: "achète", r: "achète — e muet → è tréma (graphie aisée / rectifiée 1990 acceptée aussi : achète préféré)" },
  "achetes": { s: "achètes", r: "achètes" },
  "achetons": { s: "achetons" },
  "achetez": { s: "achetez" },
  "achetent": { s: "achètent", r: "achètent" },
  "appeler": { s: "appeler" },
  "appele": { s: "appelle", r: "appelle — deux l aux personnes 1e/3e sg présent appeler" },
  "appeles": { s: "appelles", r: "appelles — 2e sg, deux l" },
  "appelons": { s: "appelons" },
  "appelez": { s: "appelez" },
  "appelent": { s: "appellent", r: "appellent — 3e pluriel appeler : deux l" },
  "jeter": { s: "jeter" },
  "jete": { s: "jette", r: "jette — deux t jeter→jet- 1e/3e sg" },
  "jetes": { s: "jettes", r: "jettes" },
  "jetons": { s: "jetons" },
  "jetez": { s: "jetez" },
  "jetent": { s: "jettent", r: "jettent — deux t" },
  "essayer": { s: "essayer" },
  "essaye": { s: "essaye" },
  "essaie": { s: "essaie", r: "essaye OU essaie — les deux graphies acceptées rectifiées 1990, préféré essaie" },
  "emploie": { s: "emploie" },
  "employe": { s: "employé", r: "employé — participe passé / nom masculin employé, accent aigu é obligatoire" },
  "employée": { s: "employée", r: "employée — accord féminin" },
  "employes": { s: "employés", r: "employés — pluriel" },
  "employez": { s: "employez" },
  "employent": { s: "emploient", r: "emploient — 3e pluriel, oin pas oy" },
  "broyer": { s: "broyer" },
  "bvoie": { s: "voie", r: "voie (route) vs boire (voit)" },
  "voir": { s: "voir" },
  "croire": { s: "croire" },
  "crois": { s: "crois" },
  "croit": { s: "croit", r: "croit (sans ô, orthographe rectifiée 1990)" },
  "croît": { s: "croît", r: "croît — accent circonflexe historique, deux graphies acceptées" },
  "croyez": { s: "croyez" },
  "croient": { s: "croient" },
  "croitre": { s: "croître", r: "croître — accent circonflexe traditionnel" },
  "conduire": { s: "conduire" },
  "conduis": { s: "conduis" },
  "conduit": { s: "conduit" },
  "conduisons": { s: "conduisons" },
  "conduisez": { s: "conduisez" },
  "conduisent": { s: "conduisent" },
  "conduite": { s: "conduite" },
  "construire": { s: "construire" },
  "construis": { s: "construis" },
  "construit": { s: "construit" },
  "construisons": { s: "construisons" },
  "construisez": { s: "construisez" },
  "construisent": { s: "construisent" },
  "construction": { s: "construction" },
  "apprendre": { s: "apprendre" },
  "apprends": { s: "apprends" },
  "apprend": { s: "apprend" },
  "apprenons": { s: "apprenons" },
  "apprenez": { s: "apprenez" },
  "apprennent": { s: "apprennent" },
  "appris": { s: "appris" },
  "apprise": { s: "apprise" },
  "apprises": { s: "apprises" },
  "comprendre": { s: "comprendre" },
  "comprends": { s: "comprends" },
  "comprend": { s: "comprend" },
  "comprenons": { s: "comprenons" },
  "comprenez": { s: "comprenez" },
  "comprennent": { s: "comprennent" },
  "compris": { s: "compris" },
  "comprise": { s: "comprise" },
  "comprises": { s: "comprises" },
  "prendre": { s: "prendre" },
  "prends": { s: "prends" },
  "prend": { s: "prend" },
  "prenons": { s: "prenons" },
  "prenez": { s: "prenez" },
  "prennent": { s: "prennent" },
  "pris": { s: "pris" },
  "prise": { s: "prise" },
  "prises": { s: "prises" },
  "boire": { s: "boire" },
  "bois": { s: "bois" },
  "boit": { s: "boit" },
  "buvons": { s: "buvons" },
  "buvez": { s: "buvez" },
  "boivent": { s: "boivent" },
  "bu": { s: "bu" },
  "bus": { s: "bus", r: "bus (véhicule) — invariable pluriel / bu = participe passé boire" },
  "manger": { s: "manger" },
  "mange": { s: "mange" },
  "manges": { s: "manges" },
  "mangeons": { s: "mangeons", r: "mangeons — le e survit avant ons" },
  "mangez": { s: "mangez" },
  "mangent": { s: "mangent" },
  "mangé": { s: "mangé" },
  "voyager": { s: "voyager" },
  "voyage": { s: "voyage" },
  "voyages": { s: "voyages" },
  "voyageons": { s: "voyageons" },
  "voyagez": { s: "voyagez" },
  "voyagent": { s: "voyagent" },
  "nager": { s: "nager" },
  "nage": { s: "nage" },
  "nages": { s: "nages" },
  "nageons": { s: "nageons" },
  "nagez": { s: "nagez" },
  "nagent": { s: "nagent" },
  "commencer": { s: "commencer" },
  "commence": { s: "commence", r: "commence — avant e/i on garde la c douce sans cédille; sinon commençons a cédille" },
  "commences": { s: "commences" },
  "commencons": { s: "commençons", r: "commençons — c cédille devant o pour garder son [s]" },
  "commencez": { s: "commencez" },
  "commencent": { s: "commencent" },
  "commencé": { s: "commencé" },
  "placer": { s: "placer" },
  "place": { s: "place" },
  "places": { s: "places" },
  "plaçons": { s: "plaçons", r: "plaçons — c cédille devant ons" },
  "placez": { s: "placez" },
  "placent": { s: "placent" },
  "avancer": { s: "avancer" },
  "avance": { s: "avance" },
  "avances": { s: "avances" },
  "avançons": { s: "avançons", r: "avançons — c cédille" },
  "avancez": { s: "avancez" },
  "avancent": { s: "avancent" },
  "deplacer": { s: "déplacer", r: "déplacer — é accent préfixe dé-" },
  "deplace": { s: "déplace", r: "déplace — é accent" },
  "depenser": { s: "dépenser", r: "dépenser — é accent préfixe dé-" },
  "depense": { s: "dépense", r: "dépense — nom/verbe" },
  "descendre": { s: "descendre" },
  "descente": { s: "descente" },
  "montagne": { s: "montagne" },
  "montagnes": { s: "montagnes" },
  "chateau": { s: "château", r: "château — â accent circonflexe" },
  "chateaux": { s: "châteaux", r: "châteaux — pluriel irrégulier + accent" },
  "chambre": { s: "chambre" },
  "chambres": { s: "chambres" },
  "maison": { s: "maison" },
  "maisons": { s: "maisons" },
  "appartement": { s: "appartement" },
  "appartements": { s: "appartements" },
  "immeuble": { s: "immeuble" },
  "immeubles": { s: "immeubles" },
  "rue": { s: "rue" },
  "rues": { s: "rues" },
  "avenue": { s: "avenue" },
  "avenues": { s: "avenues" },
  "boulevard": { s: "boulevard" },
  "transport": { s: "transport" },
  "transports": { s: "transports" },
  "voiture": { s: "voiture" },
  "voitures": { s: "voitures" },
  "metro": { s: "métro", r: "métro — é accent aigu" },
  "metros": { s: "métros", r: "métros" },
  "tramway": { s: "tramway" },
  "train": { s: "train" },
  "trains": { s: "trains" },
  "avion": { s: "avion" },
  "avions": { s: "avions" },
  "aeroport": { s: "aéroport", r: "aéroport — é aigu + o circonflexe" },
  "aeroports": { s: "aéroports", r: "aéroports pluriel" },
  "gare": { s: "gare" },
  "gares": { s: "gares" },
  "billet": { s: "billet" },
  "billets": { s: "billets" },
  "billeterie": { s: "billetterie", r: "billetterie — deux l" },
  "horaire": { s: "horaire" },
  "horaires": { s: "horaires" },
  "heure": { s: "heure", r: "heure — h muet + e accent aigu final" },
  "heures": { s: "heures" },
  "restaurent": { s: "restaurant", r: "restaurant — nom, DEUX T (pas un) — a final comme -ant mais avec un t de plus : res-tau-rant" },
  "restaurants": { s: "restaurants", r: "restaurants pluriel — deux t" },
  "cafe": { s: "café", r: "café — é accent aigu final" },
  "cafes": { s: "cafés", r: "cafés pluriel" },
  "boulangerie": { s: "boulangerie" },
  "boulanger": { s: "boulanger" },
  "boulangere": { s: "boulangère", r: "boulangère — è accent grave" },
  "patisserie": { s: "pâtisserie", r: "pâtisserie — â accent circonflexe" },
  "patissier": { s: "pâtissier", r: "pâtissier — â" },
  "patissiere": { s: "pâtissière", r: "pâtissière — â + è" },
  "menu": { s: "menu" },
  "plat": { s: "plat" },
  "plats": { s: "plats" },
  "cinema": { s: "cinéma", r: "cinéma — é accent final" },
  "cinemas": { s: "cinémas", r: "cinémas pluriel" },
  "film": { s: "film" },
  "films": { s: "films" },
  "theatre": { s: "théâtre", r: "théâtre — é + â accents circonflexes" },
  "theatres": { s: "théâtres", r: "théâtres pluriel" },
  "musee": { s: "musée", r: "musée — é final" },
  "musees": { s: "musées", r: "musées pluriel" },
  "bibliotheque": { s: "bibliothèque", r: "bibliothèque — ô accent + que final" },
  "bibliotheques": { s: "bibliothèques", r: "bibliothèques pluriel" },
  "librairie": { s: "librairie" },
  "librairies": { s: "librairies" },
  "magasin": { s: "magasin" },
  "magasins": { s: "magasins" },
  "magasinage": { s: "magasinage" },
  "centre": { s: "centre", r: "centre (France) — deux orthographes valides (center = Canada aussi)" },
  "centre commercial": { s: "centre commercial" },
  "supermarche": { s: "supermarché", r: "supermarché — é accent final" },
  "supermarches": { s: "supermarchés", r: "supermarchés pluriel" },
  "marche": { s: "marché", r: "marché — é accent final" },
  "marches": { s: "marchés", r: "marchés pluriel" },
  "sport": { s: "sport" },
  "sports": { s: "sports" },
  "football": { s: "football" },
  "basket": { s: "basket" },
  "musique": { s: "musique" },
  "musical": { s: "musical" },
  "musicale": { s: "musicale" },
  "musicales": { s: "musicales" },
  "musicaux": { s: "musicaux", r: "musicaux — pluriel musical → musicaux -al→-aux" },
  "artiste": { s: "artiste" },
  "artistes": { s: "artistes" },
  "peintre": { s: "peintre" },
  "peintres": { s: "peintres" },
  "tableau": { s: "tableau" },
  "tableaux": { s: "tableaux", r: "tableaux — pluriel irrégulier tableau → tableaux (pas de x de plus)" },
  "tableaus": { s: "tableaux", r: "tableaux pluriel -eau → -eaux jamais -eaus" },
  "pinceau": { s: "pinceau" },
  "pinceaux": { s: "pinceaux", r: "pinceaux -eau → -eaux" },
  "cheveaux": { s: "cheveux", r: "cheveux — orthographe exacte cheveux (e au x) chevaux = chevaux du cheval" },
  "cheveux": { s: "cheveux" },
  "oeil": { s: "œil", r: "œil — o dans e ligaturé" },
  "yeux": { s: "yeux", r: "yeux — pluriel irrégulier œil → yeux" },
  "doigt": { s: "doigt" },
  "doigts": { s: "doigts" },
  "main": { s: "main" },
  "mains": { s: "mains" },
  "pied": { s: "pied" },
  "pieds": { s: "pieds" },
  "coeur": { s: "cœur", r: "cœur — œ ligaturé + â accent" },
  "coeurs": { s: "cœurs", r: "cœurs pluriel" },
  "bonheur": { s: "bonheur" },
  "malheur": { s: "malheur" },
  "succès": { s: "succès" },
  "succes": { s: "succès", r: "succès — accent grave final obligatoire pour le nom" },
  "succees": { s: "succès", r: "succès — deux c + è accent final" },
  "progres": { s: "progrès", r: "progrès — è accent final (nom masculin progrès)" },
  "accès": { s: "accès" },
  "acces": { s: "accès", r: "accès — accent grave final + deux c" },
  "degre": { s: "degré", r: "degré — è accent final" },
  "degres": { s: "degrés", r: "degrés pluriel" },
  "tresors": { s: "trésors" },
  "eglise": { s: "église", r: "église — é accent aigu + grave" },
  "eglises": { s: "églises", r: "églises pluriel" },
  "cloitre": { s: "cloître", r: "cloître — î accent circonflexe" },
  "salle": { s: "salle" },
  "salles": { s: "salles" },
  "sallon": { s: "salon", r: "salon (pièce) / salle" },
  "salon": { s: "salon" },
  "salons": { s: "salons" },
  "assister": { s: "assister" },
  "participer": { s: "participer" },
  "participez": { s: "participez" },
  "participent": { s: "participent" },
  "participation": { s: "participation" },
  "reussir": { s: "réussir", r: "réussir — é accent aigu + deux s" },
  "reussi": { s: "réussi", r: "réussi — participe passé masculin" },
  "reussie": { s: "réussie", r: "réussie — accord féminin" },
  "reussis": { s: "réussis", r: "réussis — pluriel masc / 2e sg présent" },
  "reussies": { s: "réussies", r: "réussies — accord féminin pluriel" },
  "reussite": { s: "réussite", r: "réussite — nom féminin" },
  "echouer": { s: "échouer", r: "échouer — é accent aigu é-" },
  "echoue": { s: "échoue", r: "échoue" },
  "echec": { s: "échec", r: "échec — é accent aigu é-" },
  "echecs": { s: "échecs", r: "échecs pluriel" },
  "essai": { s: "essai" },
  "essais": { s: "essais", r: "essais pluriel (invariable s — jamais -x)" },
  "essaix": { s: "essais", r: "essais pluriel orthographe exacte" },
  "changement": { s: "changement" },
  "changer": { s: "changer" },
  "modifier": { s: "modifier" },
  "créer": { s: "créer" },
  "creer": { s: "créer", r: "créer — é accent aigu" },
  "cree": { s: "crée", r: "crée — 1e/3e sg présent / participe passé" },
  "creation": { s: "création", r: "création — é accent" },
  "créativité": { s: "créativité" },
  "innovatif": { s: "innovatif" },
  "innovation": { s: "innovation" },
  "nouveaute": { s: "nouveauté", r: "nouveauté — â accent + é final" },
  "nouveautes": { s: "nouveautés", r: "nouveautés pluriel" },
  "idee": { s: "idée", r: "idée — deux é accents aigus" },
  "idees": { s: "idées", r: "idées pluriel" },
  "probleme": { s: "problème", r: "problème — è accent grave sur le è" },
  "problemes": { s: "problèmes", r: "problèmes pluriel" },
  "système": { s: "système" },
  "systeme": { s: "système", r: "système — è accent grave + y grec" },
  "systemes": { s: "systèmes", r: "systèmes pluriel" },
  "logiciel": { s: "logiciel" },
  "logiciels": { s: "logiciels" },
  "ordinateur": { s: "ordinateur" },
  "ordinateurs": { s: "ordinateurs" },
  "internet": { s: "Internet", r: "Internet — nom propre, capitale" },
  "courriel": { s: "courriel" },
  "courriels": { s: "courriels" },
  "reseau": { s: "réseau", r: "réseau — é aigu + â circonflexe" },
  "reseaux": { s: "réseaux", r: "réseaux pluriel -eau → -eaux + accents" },
  "site": { s: "site" },
  "sites": { s: "sites" },
  "application": { s: "application" },
  "applications": { s: "applications" },
  "appli": { s: "appli" },
  "applis": { s: "applis" },
  "telephone": { s: "téléphone", r: "téléphone — é aigu préfixe télé-" },
  "telephones": { s: "téléphones", r: "téléphones pluriel" },
  "television": { s: "télévision", r: "télévision — é aigu télé-" },
  "televisions": { s: "télévisions", r: "télévisions pluriel" },
  "travailleur": { s: "travailleur" },
  "travailleuse": { s: "travailleuse" },
  "femme": { s: "femme" },
  "femmes": { s: "femmes" },
  "homme": { s: "homme" },
  "hommes": { s: "hommes" },
  "enfant": { s: "enfant" },
  "enfants": { s: "enfants" },
  "parent": { s: "parent" },
  "parents": { s: "parents" },
  "famille": { s: "famille" },
  "familles": { s: "familles" },
  "ami": { s: "ami" },
  "amie": { s: "amie" },
  "amis": { s: "amis" },
  "amies": { s: "amies" },
  "amitié": { s: "amitié", r: "amitié — â accent + tié" },
  "amour": { s: "amour" },
  "argent": { s: "argent" },
  "economie": { s: "économie", r: "économie — é accent aigu éco-" },
  "economies": { s: "économies", r: "économies pluriel" },
  "economique": { s: "économique", r: "économique — é accent" },
  "pauvre": { s: "pauvre" },
  "riche": { s: "riche" },
  "richesse": { s: "richesse" },
  "dette": { s: "dette" },
  "dettes": { s: "dettes" },
  "impot": { s: "impôt", r: "impôt — ô accent circonflexe final" },
  "impots": { s: "impôts", r: "impôts pluriel" },
  "salaire": { s: "salaire" },
  "salaires": { s: "salaires" },
  "loyer": { s: "loyer" },
  "loyers": { s: "loyers" },
  "caution": { s: "caution" },
  "contre": { s: "contre" },
  "cause": { s: "cause" },
  "causes": { s: "causes" },
  "effet": { s: "effet" },
  "effets": { s: "effets" },
  "facon": { s: "façon", r: "façon — ç cédille c sous cédille" },
  "facons": { s: "façons", r: "façons pluriel" },
  "façonner": { s: "façonner" },
  "garcon": { s: "garçon", r: "garçon — ç cédille obligatoire" },
  "garcons": { s: "garçons", r: "garçons pluriel" },
  "lecon": { s: "leçon", r: "leçon — ç cédille + ç final accent leçon" },
  "lecons": { s: "leçons", r: "leçons pluriel" },
  "reception": { s: "réception", r: "réception — é accent aigu + ç cédille (reception sans ç = orthographe invalide)" },
  "receptions": { s: "réceptions", r: "réceptions pluriel" },
  "exception": { s: "exception", r: "exception — sans accent, p + t sans ç (ceci est la règle exception = ption sans ç)" },
  "exceptions": { s: "exceptions" },
  "relation": { s: "relation" },
  "relations": { s: "relations" },
  "connexion": { s: "connexion", r: "connexion — x, pas de double n / connexion avec deux n aussi possible (connexion = plus courant canada/qc)" },
  "connection": { s: "connexion", r: "connexion — graphie préférée en français canadien/européen (connection = anglicisme orthographe rare)" },
  "experience": { s: "expérience", r: "expérience — é accent aigu sur ex-, périence avec è accent" },
  "experiences": { s: "expériences", r: "expériences pluriel" },
  "différence": { s: "différence", r: "différence — è accent grave" },
  "difference": { s: "différence", r: "différence — accent grave sur è" },
  "differences": { s: "différences", r: "différences pluriel" },
  "influence": { s: "influence" },
  "influences": { s: "influences" },
  "reference": { s: "référence", r: "référence — deux é accents aigus" },
  "references": { s: "références", r: "références pluriel" },
  "presence": { s: "présence", r: "présence — é accent aigu + è sur le è" },
  "présence": { s: "présence" },
  "absence": { s: "absence" },
  "exigence": { s: "exigence" },
  "exigences": { s: "exigences" },
  "urgence": { s: "urgence" },
  "urgences": { s: "urgences" },
  "tendance": { s: "tendance" },
  "tendances": { s: "tendances" },
  "competence": { s: "compétence", r: "compétence — é aigu + è accents (non négociable colonnes DB ENUM)" },
  "competences": { s: "compétences", r: "compétences pluriel" },
  "connaissance": { s: "connaissance" },
  "connaissances": { s: "connaissances" },
  "naissance": { s: "naissance" },
  "renaissance": { s: "renaissance" },
  "reconnaissance": { s: "reconnaissance" },
  "messagerie": { s: "messagerie" },
  "message": { s: "message" },
  "messages": { s: "messages" },
  "messager": { s: "messager" },
  "messagère": { s: "messagère" },
  "collègue": { s: "collègue", r: "collègue — è accent grave + deux g" },
  "collegue": { s: "collègue", r: "collègue — orthographe valide sans accents est invalide, faut les deux è + accents" },
  "collegues": { s: "collègues", r: "collègues pluriel" },
  "employé": { s: "employé" },
  "collaborateur": { s: "collaborateur" },
  "collaboratrice": { s: "collaboratrice" },
  "collaborateurs": { s: "collaborateurs" },
  "client": { s: "client" },
  "cliente": { s: "cliente" },
  "clients": { s: "clients" },
  "clientes": { s: "clientes" },
  "usager": { s: "usager" },
  "usagère": { s: "usagère" },
  "usagers": { s: "usagers" },
  "utilisateur": { s: "utilisateur" },
  "utilisatrice": { s: "utilisatrice" },
  "utilisateurs": { s: "utilisateurs" },
  "utilisatrices": { s: "utilisatrices" },
  "public": { s: "public" },
  "publique": { s: "publique" },
  "publiques": { s: "publiques" },
  "publics": { s: "publics" },
  "privé": { s: "privé" },
  "prive": { s: "privé", r: "privé — é accent final obligatoire" },
  "privés": { s: "privés" },
  "privee": { s: "privée", r: "privée — accord féminin + é accent" },
  "privees": { s: "privées", r: "privées féminin pluriel" },
  "opportunité": { s: "opportunité", r: "opportunité — accent final é/ti? o = op por tu ni té accent final obligatoire (opportunità italien, français = opportunité)" },
  "opportunite": { s: "opportunité", r: "opportunité — accent final manquant" },
  "opportunites": { s: "opportunités", r: "opportunités pluriel" },
  "développement": { s: "développement" },
  "developpement": { s: "développement", r: "développement — é accent sur le premier é + deux p + deux l (p p)" },
  "developpements": { s: "développements", r: "développements pluriel" },
  "developpeur": { s: "développeur", r: "développeur — é accent aigu préfixe dé- + deux p" },
  "développeuse": { s: "développeuse" },
  "developpeuse": { s: "développeuse", r: "développeuse — féminin développeur + accents" },
  "developpeurs": { s: "développeurs", r: "développeurs pluriel" },
  "developpeuses": { s: "développeuses", r: "développeuses féminin pluriel" },
  "techonologie": { s: "technologie", r: "technologie — on garde nol pas ono" },
  "techonologies": { s: "technologies", r: "technologies — orthographe exacte techNOlogie" },
  "recherche": { s: "recherche" },
  "recherches": { s: "recherches" },
  "recherché": { s: "recherché" },
  "chercheur": { s: "chercheur" },
  "chercheuse": { s: "chercheuse" },
  "analyse": { s: "analyse", r: "analyse — s entre deux voyelles prononce [z] (graphie préférée)" },
  "analyser": { s: "analyser" },
  "analyses": { s: "analyses" },
  "resultat": { s: "résultat", r: "résultat — é accent aigu sur ré + ú accent aigu sur ul" },
  "resultats": { s: "résultats", r: "résultats pluriel" },
  "objectif": { s: "objectif" },
  "objectifs": { s: "objectifs" },
  "but": { s: "but" },
  "buts": { s: "buts" },
  "besoin": { s: "besoin" },
  "besoins": { s: "besoins" },
  "manque": { s: "manque" },
  "manques": { s: "manques" },
  "manquant": { s: "manquant" },
  "solution": { s: "solution" },
  "solutions": { s: "solutions" },
  "question": { s: "question" },
  "questions": { s: "questions" },
  "questionner": { s: "questionner" },
  "explication": { s: "explication" },
  "explications": { s: "explications" },
  "expliquer": { s: "expliquer" },
  "définition": { s: "définition" },
  "definition": { s: "définition", r: "définition — é accent aigu dé-" },
  "definitions": { s: "définitions", r: "définitions pluriel" },
  "description": { s: "description" },
  "descriptions": { s: "descriptions" },
  "decrire": { s: "décrire", r: "décrire — é accent aigu sur dé-" },
  "décrit": { s: "décrit" },
  "introduction": { s: "introduction" },
  "introduire": { s: "introduire" },
  "conclusion": { s: "conclusion" },
  "conclure": { s: "conclure" },
  "concluons": { s: "concluons" },
  "concluez": { s: "concluez" },
  "concluent": { s: "concluent" },
  "conclu": { s: "conclu", r: "conclu = participe passé irrégulier conclure → conclu" },
  "conclue": { s: "conclue", r: "conclue accord féminin" },
  "conclus": { s: "conclus", r: "conclus pluriel masc / 2e sg" },
  "conclues": { s: "conclues", r: "conclues accord féminin pluriel" },
  "argumenter": { s: "argumenter" },
  "argument": { s: "argument" },
  "arguments": { s: "arguments" },
  "exemple": { s: "exemple" },
  "exemples": { s: "exemples" },
  "preuve": { s: "preuve" },
  "preuves": { s: "preuves", r: "preuves — è accent sur preuves pluriel féminin (preuves = preuves orthographe oublié è = é preuves? Preuve → è, préuve → é+û. Pour preuve : orthographe traditionnelle 'preuve' sans accent. Parfait." },
  "démontrer": { s: "démontrer" },
  "demontrer": { s: "démontrer", r: "démontrer — ô accent circonflexe sur mon" },
  "démontre": { s: "démontre" },
  "demontre": { s: "démontre", r: "démontre — ô accent manquant" },
  "illustrer": { s: "illustrer" },
  "illustration": { s: "illustration" },
  "illustrations": { s: "illustrations" },
  "refuter": { s: "réfuter", r: "réfuter — é accent aigu ré-" },
  "refuté": { s: "réfuté" },
  "approuver": { s: "approuver" },
  "approuvé": { s: "approuvé" },
  "desapprouver": { s: "désapprouver", r: "désapprouver — é accent dés-" },
  "autoriser": { s: "autoriser" },
  "autorisé": { s: "autorisé" },
  "permettre": { s: "permettre" },
  "permet": { s: "permet" },
  "permettent": { s: "permettent" },
  "permis": { s: "permis" },
  "permise": { s: "permise" },
  "permises": { s: "permises" },
  "obliger": { s: "obliger" },
  "obligé": { s: "obligé" },
  "devoir": { s: "devoir" },
  "dû": { s: "dû", r: "dû — dû circonflexe û obligatoire pour participe passé masculin devoir" },
  "du": { s: "du", r: "du — article contracté de + le (pas d'accent). Participe passé = dû" },
  "dus": { s: "dûs", r: "dûs — participe passé pluriel masculin" },
  "due": { s: "due", r: "due / dûe — deux graphies acceptées; dûe avec accent recommandé pour distinguer l'adjectif féminin" },
  "dûe": { s: "dûe" },
  "dues": { s: "dûes", r: "dûes — accord féminin pluriel de dû avec accent circonflexe recommandé" },
  "pouvoir": { s: "pouvoir" },
  "savoir": { s: "savoir" },
  "vouloir": { s: "vouloir" },
  "voulu": { s: "voulu" },
  "voulue": { s: "voulue" },
  "voulus": { s: "voulus" },
  "voulues": { s: "voulues" },
  "falloir": { s: "falloir" },
  "faut": { s: "faut" },
  "fallu": { s: "fallu" },
  "pleuvoir": { s: "pleuvoir" },
  "pleut": { s: "pleut" },
  "valoir": { s: "valoir" },
  "vaut": { s: "vaut" },
  "valu": { s: "valu" },
  "mourir": { s: "mourir" },
  "meurt": { s: "meurt" },
  "meurent": { s: "meurent" },
  "mort": { s: "mort" },
  "morte": { s: "morte" },
  "morts": { s: "morts" },
  "mortes": { s: "mortes" },
  "courir": { s: "courir" },
  "court": { s: "court" },
  "courons": { s: "courons" },
  "courez": { s: "courez" },
  "courent": { s: "courent" },
  "couru": { s: "couru" },
  "courue": { s: "courue" },
  "courus": { s: "courus" },
  "courues": { s: "courues" },
  "dormir": { s: "dormir" },
  "dors": { s: "dors" },
  "dort": { s: "dort" },
  "dormons": { s: "dormons" },
  "dormez": { s: "dormez" },
  "dorment": { s: "dorment" },
  "dormi": { s: "dormi" },
  "sentir": { s: "sentir" },
  "sens": { s: "sens" },
  "sent": { s: "sent" },
  "sentons": { s: "sentons" },
  "sentez": { s: "sentez" },
  "sentent": { s: "sentent" },
  "senti": { s: "senti" },
  "sentie": { s: "sentie" },
  "sentis": { s: "sentis" },
  "senties": { s: "senties" },
  "mentir": { s: "mentir" },
  "mens": { s: "mens" },
  "ment": { s: "ment" },
  "mentons": { s: "mentons" },
  "mentez": { s: "mentez" },
  "mentent": { s: "mentent" },
  "menti": { s: "menti" },
  "servir": { s: "servir" },
  "sers": { s: "sers" },
  "sert": { s: "sert" },
  "servons": { s: "servons" },
  "servez": { s: "servez" },
  "servent": { s: "servent" },
  "servi": { s: "servi" },
  "servie": { s: "servie" },
  "servis": { s: "servis" },
  "servies": { s: "servies" },
  "fuir": { s: "fuir" },
  "fuis": { s: "fuis" },
  "fuit": { s: "fuit" },
  "fuyons": { s: "fuyons" },
  "fuyez": { s: "fuyez" },
  "fuient": { s: "fuient" },
  "ouvrir": { s: "ouvrir" },
  "ouvre": { s: "ouvre" },
  "ouvres": { s: "ouvres" },
  "ouvrons": { s: "ouvrons" },
  "ouvrez": { s: "ouvrez" },
  "ouvrent": { s: "ouvrent" },
  "ouvert": { s: "ouvert" },
  "ouverte": { s: "ouverte" },
  "ouverts": { s: "ouverts" },
  "ouvertes": { s: "ouvertes" },
  "couvrir": { s: "couvrir" },
  "couvre": { s: "couvre" },
  "couvres": { s: "couvres" },
  "couvrons": { s: "couvrons" },
  "couvrez": { s: "couvrez" },
  "couvrent": { s: "couvrent" },
  "couvert": { s: "couvert" },
  "couverte": { s: "couverte" },
  "couverts": { s: "couverts" },
  "couvertes": { s: "couvertes" },
  "decouvrir": { s: "découvrir", r: "découvrir — é accent aigu dé-" },
  "decouvre": { s: "découvre", r: "découvre — é accent" },
  "offrir": { s: "offrir" },
  "offre": { s: "offre" },
  "offres": { s: "offres" },
  "offrons": { s: "offrons" },
  "offrez": { s: "offrez" },
  "offrent": { s: "offrent" },
  "offert": { s: "offert" },
  "offerte": { s: "offerte" },
  "offerts": { s: "offerts" },
  "offertes": { s: "offertes" },
  "souffrir": { s: "souffrir" },
  "souffre": { s: "souffre" },
  "souffres": { s: "souffres" },
  "souffrons": { s: "souffrons" },
  "souffrez": { s: "souffrez" },
  "souffrent": { s: "souffrent" },
  "souffert": { s: "souffert" },
  "accepter": { s: "accepter" },
  "accepté": { s: "accepté" },
  "refuser": { s: "refuser" },
  "refusé": { s: "refusé" },
  "inviter": { s: "inviter" },
  "invité": { s: "invité" },
  "remercier": { s: "remercier" },
  "remerciment": { s: "remerciement" },
  "remerciments": { s: "remerciements" },
  "feliciter": { s: "féliciter", r: "féliciter — é accent aigu fé-" },
  "felicitations": { s: "félicitations", r: "félicitations — é accent aigu pluriel" },
  "excuser": { s: "excuser" },
  "excuse": { s: "excuse" },
  "excuses": { s: "excuses" },
  "pardonner": { s: "pardonner" },
  "pardon": { s: "pardon" },
  "pardonne": { s: "pardonne" },
  "pardonnez": { s: "pardonnez" },
  "sil": { s: "s'il", r: "s'il — contraction si + il, apostrophe OBLIGATOIRE (sil = anglicisme, orthographe invalide)" },
  "sils": { s: "s'ils", r: "s'ils — pluriel s'ils (apostrophe obligatoire)" },
  "sil vous plait": { s: "s'il vous plaît", r: "s'il vous plaît — 4 mots : s'il + vous + plaît, avec î circonflexe sur plaît" },
  "svp": { s: "s'il vous plaît", r: "Évitez les sigles, écrivez s'il vous plaît" },
  "stp": { s: "s'il te plaît", r: "Écrivez s'il te plaît, évitez sigle STP" },
  "aujourdhuis": { s: "aujourd'hui", r: "aujourd'hui est un adverbe invariable, pas de s pluriel" },
  "tout a coup": { s: "tout à coup", r: "tout à coup — deux accents graves sur à (expression figée, 3 mots)" },
  "touta coup": { s: "tout à coup", r: "tout à coup — écrit en 3 mots" },
  "tout de suite": { s: "tout de suite", r: "tout de suite — DE 3 mots, pas un toutdesuite" },
  "toutsuite": { s: "tout de suite", r: "tout de suite — 3 mots séparés" },
  "parce que": { s: "parce que", r: "parce que — 2 mots, jamais parceque ou parce-que" },
  "parceque": { s: "parce que", r: "parce que — 2 mots (erreur fréquente collée)" },
  "pcq": { s: "parce que", r: "Évitez sigle pcq, écrivez parce que" },
  "pq": { s: "pourquoi", r: "Pourquoi pas abréviation" },
  "afin de": { s: "afin de" },
  "afinque": { s: "afin que", r: "afin que — 2 mots + subjonctif après" },
  "bien que": { s: "bien que", r: "bien que — 2 mots + subjonctif après" },
  "bienque": { s: "bien que", r: "bien que séparément" },
  "malgre": { s: "malgré", r: "malgré — é accent final, UN MOT (seul), jamais malgrés" },
  "malgres": { s: "malgré", r: "malgré — invariable, pas de s final pluriel" },
  "malgré que": { s: "bien que / en dépit de", r: "malgré que est considéré comme impropre par la majorité des grammairiens contemporains, on utilise 'bien que' + subjonctif, ou 'malgré le fait que + indicatif" },
  "en depit de": { s: "en dépit de", r: "en dépit de — é accent aigu sur dé" },
  "a cote de": { s: "à côté de", r: "à côté de — à préposition + ô accent sur côté (espacement correct: 4 mots)" },
  "acotéde": { s: "à côté de", r: "à côté de — 4 mots séparés" },
  "a cote": { s: "à côté", r: "à côté — 2 mots + accents obligatoires" },
  "pourquoi pas": { s: "pourquoi pas" },
  "c est": { s: "c'est", r: "c'est — contraction ce + est, apostrophe OBLIGATOIRE" },
  "cest": { s: "c'est", r: "c'est — il faut une apostrophe (cest = orthographe invalide)" },
  "saurait": { s: "saurait" },
  "peut-etre": { s: "peut-être", r: "peut-être — trait d'union + è accent grave sur être" },
  "peutetre": { s: "peut-être", r: "peut-être — trait d'union ET accent" },
  "peut être": { s: "peut-être", r: "adverbe 'peut-être' s'écrit avec trait d'union" },
  "longtemps": { s: "longtemps", r: "longtemps — p + s en un mot (longtems est fautif)" },
  "longtems": { s: "longtemps", r: "longtemps orthographe exacte" },
  "souvent": { s: "souvent" },
  "toujour": { s: "toujours", r: "toujours — s final obligatoire" },
  "tous les jours": { s: "tous les jours", r: "tous les jours — trois mots (fréquence), pas 'toujours' pour tous les jours" },
  "tout les jours": { s: "tous les jours", r: "tous les jours (masculin pluriel accord : tous, pas tout)" },
  "tout le monde": { s: "tout le monde", r: "tout le monde invariable, toujours singulier tout masc sg" },
  "tous le monde": { s: "tout le monde", r: "tout le monde — accord singulier 'tout' car 'monde' singulier" },
  "quelquefois": { s: "quelquefois", r: "quelquefois UN MOT, parfois = parfois, quelques fois = 3 mots si dénombrable" },
  "parfois": { s: "parfois" },
  "toujours": { s: "toujours" },
  "jamais": { s: "jamais" },
  "jamaism": { s: "jamais", r: "jamais pas plus de m, jamais = j + a + mais (deuxième s? 'jamais' exact j-a-m-a-i-s)" },
  "ne...pas": { s: "ne pas", r: "ne + verbe + pas → deux éléments de négation" },
  "je ne sais pas": { s: "je ne sais pas" },
  "jsp": { s: "je ne sais pas", r: "JSP = registre oral, à l'écrit écrivez 'je ne sais pas'" },
  "y": { s: "y" },
  "en": { s: "en" },
  "il y a": { s: "il y a", r: "il y a — 3 mots, durée" },
  "ilya": { s: "il y a", r: "il y a 3 mots séparés" },
  "il ya": { s: "il y a", r: "il y a avec petit y séparé de a" },
  "il y en a": { s: "il y en a" },
  "j ai": { s: "j'ai", r: "j'ai — contraction je + ai, apostrophe obligatoire" },
  "jai": { s: "j'ai", r: "j'ai — il faut une apostrophe (jai = faute)" },
  "j aime": { s: "j'aime", r: "j'aime — apostrophe obligatoire" },
  "jaime": { s: "j'aime", r: "j'aime avec apostrophe" },
  "n est": { s: "n'est", r: "n'est — ne + est contraction, apostrophe obligatoire" },
  "nest": { s: "n'est", r: "n'est avec apostrophe" },
  "l ecole": { s: "l'école", r: "l'école — apostrophe l'+ é cole élision voyelle" },
  "d abord": { s: "d'abord", r: "d'abord — apostrophe élision devant a" },
  "bon apetit": { s: "bon appétit", r: "bon appétit — appétit avec a accent aigu, puis ti final" },
  "bon appétit": { s: "bon appétit" },
  "appétit": { s: "appétit" },
  "appetit": { s: "appétit", r: "appétit — é accent aigu + î accent" },
  "deguster": { s: "déguster", r: "déguster — é accent aigu dé- + û accent circonflexe sur goûter" },
  "degustation": { s: "dégustation", r: "dégustation — é accent dé-" },
};

// ---------------------------------------------------------------------------
// Dédoublonnage minimal : clefs dupliquées via ré-écriture à la main au-dessus
// On valide seulement au runtime : ERRORS_EXACT_LOWER en clef lower => suggestion
// ---------------------------------------------------------------------------

const diacriticFold = (s: string): string =>
  s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();

// Build regex alternation of EXACT entries for FAST match (compiled once per call context reuse)
let _cachedReg: RegExp | null = null;
const getReg = (): RegExp => {
  if (_cachedReg) return _cachedReg;
  const keys = Object.keys(ERRORS_EXACT_LOWER).filter((k) => k.length >= 2);
  keys.sort((a, b) => b.length - a.length);
  const escaped = keys.map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  _cachedReg = new RegExp("\\b(" + escaped.join("|") + ")\\b", "gi");
  return _cachedReg;
};

export const FR_COMMON_SPELL_ERRORS = ERRORS_EXACT_LOWER;

export type SpellOptions = {
  includeRule?: boolean;
  maxMatches?: number;
  // Allow diacritic-less near-match correction? Off by default, use exact casefold dict
  diacriticNearMatch?: boolean;
};

export function analyseOrthographe(
  text: string,
  opts: SpellOptions = {}
): SpellMatch[] {
  if (!text || text.length < 2) return [];
  const out: SpellMatch[] = [];
  const reg = getReg();
  const max = opts.maxMatches ?? 400;
  let m: RegExpExecArray | null;
  reg.lastIndex = 0;
  let iter = 0;
  while ((m = reg.exec(text)) !== null && iter < max) {
    iter++;
    const wrongFull = m[1];
    const lower = wrongFull.toLowerCase();
    const entry = ERRORS_EXACT_LOWER[lower];
    if (!entry) continue;
    // Suggestion = identité → skip (faux positif: entrée identique dans dict pour raisons de cohérence)
    if (entry.s && entry.s.toLowerCase() === lower) continue;
    const start = m.index + m[0].indexOf(wrongFull);
    const end = start + wrongFull.length;
    // Preserve capitalization? We don't for now; just use suggestion raw.
    out.push({
      start,
      end,
      wrong: wrongFull,
      suggestion: entry.s,
      rule: opts.includeRule ? entry.r || undefined : undefined,
    });
  }
  if (!opts.diacriticNearMatch) return out;
  // Second pass for diacritic near-matches (e.g., "etre" already in exact dict above, so rarely used)
  const toks = tokensOf(text);
  for (let k = 0; k < toks.length && out.length < max; k++) {
    const t = toks[k];
    const fold = diacriticFold(t.w);
    if (ERRORS_EXACT_LOWER[LIGNE(t.w)]) continue;
    // Check folded matches any known correction diacritic-folded (one-to-one):
    const candidateKey = Object.keys(ERRORS_EXACT_LOWER).find(
      (key) => diacriticFold(key) === fold && diacriticFold(ERRORS_EXACT_LOWER[key].s) === fold
    );
    if (candidateKey) {
      const suggestion = ERRORS_EXACT_LOWER[candidateKey].s;
      if (suggestion.toLowerCase() !== t.w.toLowerCase()) {
        out.push({
          start: t.i,
          end: t.i + t.l,
          wrong: t.w,
          suggestion,
          rule: opts.includeRule
            ? ERRORS_EXACT_LOWER[candidateKey].r || "Accents manquants"
            : undefined,
        });
      }
    }
  }
  // Stable sort by start index
  out.sort((a, b) => a.start - b.start);
  // Filter overlaps: if next.start < prev.end (keep first)
  const dedup: SpellMatch[] = [];
  let lastEnd = -1;
  for (const m2 of out) {
    if (m2.start >= lastEnd) {
      dedup.push(m2);
      lastEnd = m2.end;
    }
  }
  return dedup;
}
